### ISSUE TITLE
[Question] Right way for support third party plugins without affect performance

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1190]
I like Nebula for its performance, other starter themes has support for third party plugins that probably never will be installed (Woocommerce, Buddypress, etc) and adds a lot of extra templates and resources (css and js) and sometimes does not check if those plugins are available and load all resources for a simple blog theme

I want to add support for easy digital downloads and some of his plugins using nebula buit in features (for example, if user is searching inside the shop url, only recommend other products instead to include blog posts in recommendations) and without affect Nebula and letting them overwritable from Nebula child

What is the best method to add support for third party plugins on this way?

**Comment by chrisblakley** [comment]
I might need some clarification on this. Nebula (as far as I've seen) has played nicely with plugins. Most Nebula function open with an override filter that allows them to be disable or re-written, so that may help if needing to integrate plugins with things like search.

I'm focusing on completely overhauling the [documentation website now](http://gearside.com/nebula/new/), so once that is finished it might help with the integration you're working on.

**Comment by rubengc** [comment]
I think we can close this, there is no form in WordPress to modularize themes (also It breaks the template engine) so I prefer keep nebula as base theme than a overloaded theme trying to infinite plugins

If you are done this issue can be closed

**Comment by rubengc** [comment]
I searched about that and the unique option to make this is though plugins (a methodology called grandchild theme)

I am not sure if you are interested on add support to, for example, woocommerce though a plugin

You can read a bit more about grandchild themes [here](https://docs.appthemes.com/tutorials/creating-grandchild-themes/)

What do you think?
