### ISSUE TITLE
Switch options inputs

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1217]
Options that uses a select with options (enable, disable) could be a checkbox to improve, first, the visibility of options enabled/disabled and there is more easy to switch this options and in label, notice the default value

If you are ok, I could add this change to the OOP version of options right now

**Comment by chrisblakley** [comment]
That's probably a good thought (I'd say radios rather than checkboxes). If you wanted to make a PR for it feel free- I might not merge it right away but it probably is the better UX.

I've thought about redesigning the options page overall (I'll post a screenshot of what I'm sort of shooting for, but I can't find it right now).

**Comment by rubengc** [comment]
Mark as next before finish with nebula OOP, improve dir structure and finish the customizer
