### ISSUE TITLE
Integrate CMB2 and some extra plugins of CMB2 as library

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1223]
Nebula is based on become an advanced starter theme with some utilities (ga, autocomplete, infinite load, scss compiler)

In all my projects I usually needs add fields in some areas (frontend and backend) and I normally include Custom Metaboxes 2 as library and some useful extensions like tabs or post relationship fields

Also you have some fields in backend under nebula options page and this extension could help you to reduce a lot of extra work you need

Do you like the idea?

**Comment by chrisblakley** [comment]
I have [Advanced Custom Fields](https://wordpress.org/plugins/advanced-custom-fields/) bundled with Nebula currently. This seems similar- unless I'm misunderstanding it's purpose?

**Comment by rubengc** [comment]
Oh but you are not using It right? I talk about Cmb2 because is fully open source (included avanced fields)

I tested It in multiple projects and It was really easy to use and flexible when i want to build my own fields

Just we need to see what you prefer to implement in nebula

**Comment by rubengc** [comment]
A note:

I used Cmb2 because It was designed to use completely in code, It not adds any view to build your fields or anything like this

**Comment by chrisblakley** [comment]
ACF is actually one of the most used plugins that is bundled- I didn't use it much on the old documentation site, but the new docs (and most of my client work) uses it quite a bit.

The Nebula parent theme doesn't use it because (my same rule with all 3rd party libraries) it must be able to work without it.

**Comment by rubengc** [comment]
Where is acf in nebula? Or you are talking about your local install?

I think it could be useful for anyone will use nebula and also for plugin development to nebula

Sass compiler is a great resource for development and It is based on a third party library like device detection so I think a form generator will be good too

**Comment by chrisblakley** [comment]
ACF is bundled in [nebula_automation.php](https://github.com/chrisblakley/Nebula/blob/master/functions/nebula_automation.php#L43-L47) so that it can be installed on theme activation alongside the other recommended plugins.

Can you elaborate on what you're thinking for a form generator? I'm a little hesitant because I've never needed one before (I typically use Contact Form 7 to build forms). In an effort to keep Nebula light, maybe a completely separate (external) Bootstrap Form Generator tool would suffice? Maybe something like that already exists somewhere?

**Comment by rubengc** [comment]
For example for the nebula options page you have needed to write a lot of html code to build it

Options page in WordPress has different classes and form structure like needed to build forms on any post type metaboxes or on user profile form

Same happens in frontend with bootstrap and in Cmb2 you can define what structure use in each view and we can add support to bootstrap forms (sure there is a extension that already does this)

So, if you need a text field on an options page, or on a metabox or on user profile or on a frontend page you can do It with the same code semantic that provides cmb2

**Comment by rubengc** [comment]
Check also:
https://github.com/htmlburger/carbon-fields
