### ISSUE TITLE
Introduce to Nebula Plugins Manager

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1275]
Nebula has a some built-in functionalities that are a good candidates to become third party plugins and come out from the main theme, there is a list of current built-in plugins

- Woocommerce (currently ecommerce)
- Disqus (comment replacement)
- Hubspot
- Visitors

Already are third party plugins like nebula-edd (Easy Digital Downloads integration)

The idea is create a plugin that automatically offers the list of available plugins for nebula and handle automatic updates to activated ones because will be difficult get nebula plugins at wordpress.org

Also offer information for developers to references about plugin development in nebula (urls to nebula docs) and a direct link to get nebula plugin boilerplate

**Comment by chrisblakley** [comment]
Yeah this is definitely on the docket. Visitors DB will probably be the first to move. I gotta figure out what to do with Hubspot- I want to move it, but I also want to redo it from scratch. Disqus could move as well, but it actually is a very minor integration.

Only one I'm hesitant to move is the WooCommerce one since the analytics are so ingrained with Nebula, but definitely on the list to consider. We can use this issue for all of the high-level Advanced Plugin discussion.

**Comment by rubengc** [comment]
Woocommerce integration could be turned into something like EDD integration, adding some style fixes and functionalities aside from the integration with nebula analytics

if finally we add more hooks at options page nebula woocommerce and nebula edd will need to add new settings and sure more and more things will come

**Comment by chrisblakley** [comment]
Yeah we're on the same mindset. Let's get the options hooks all sorted out and then get a few Advanced Plugin integrations under our belt and then we can take another look at WooCommerce moving then.

Maybe we can use either a Github Wiki or a Github hosted page as a hub for all of the Advanced Plugins. I'll obviously link them from the Nebula Documentation as well, but would be worth having it be community-accessible.

**Comment by chrisblakley** [comment]
https://github.com/chrisblakley/Nebula/issues/1597
