### ISSUE TITLE
Get the CF7 form name/title to send to Google Analytics in event labels

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1382]
We're relying on the form ID which works, but it's a pain. I'm not sure if it's even possible, but I'd like to send the actual form name to Google Analytics somehow.

Here's my support post for this one:
https://wordpress.org/support/topic/how-to-get-the-form-title-using-javascript/

**Comment by chrisblakley** [comment]
This is close, but I don't want to deal with hidden input fields or even extra PHP:
https://stackoverflow.com/questions/37391705/how-send-form-title-contact-form-7-wp-plugin-in-hidden-input

**Comment by chrisblakley** [comment]
I modified the plugin to make this work. Here is the new support post:
https://wordpress.org/support/topic/add-form-name-to-html-and-details-object-with-working-example/

In /includes/contact-form.php, inside the form_html() function:
```php
$atts = array(
	'action' => esc_url( $url ),
	'method' => 'post',
	'class' => $class,
	'enctype' => wpcf7_enctype_value( $enctype ),
	'autocomplete' => $autocomplete,
	'novalidate' => $novalidate ? 'novalidate' : '',
	'name' => get_the_title($this->id), //Add the name of the Contact Form to the HTML output
);
```

In /includes/js/scripts.js, inside the wpcf7.submit function:
```js
var detail = {
	id: $form.closest( 'div.wpcf7' ).attr( 'id' ),
	name: $form.closest( 'div.wpcf7' ).attr( 'name' ), //Add the name of the Contact Form to the detail object
	status: 'init',
	inputs: [],
	formData: formData,
};
```

**Comment by chrisblakley** [comment]
This would probably also work to allow other plugin/theme integrations to modify form attributes without needing to bake them into CF7 itself:

Change this:
```php
$atts = wpcf7_format_atts( $atts );
```

To this:
```php
$atts = wpcf7_format_atts( apply_filters('wpcf7_form_html_attributes', $atts, $id_attr) );
```

This would add a filter before the formatting function is ran so that developers could hook in their own attributes to the plugin with something like this:

```php
//A theme or another plugin could hook into the CF7 form attributes filter with this:
add_filter('wpcf7_form_html_attributes', function($atts, $id){
	$atts['name'] = get_the_title($id);
	return $atts;
});
```

Even with this, it'd still probably need the JS solution from above to send the form name to GA. Or maybe the attribute would output to the front-end somewhere that JavaScript could grab it on submit?

**Comment by MAthez** [comment]
If you use GTM, there is another option, using the method described `[here](https://www.analyticsmania.com/post/contact-form-7-event-tracking-with-google-tag-manager/)`
It basically listens to CF7 inputs, and addds the one you choose in GTM datalayer so it can send it to GA. 
I did that to include the form name instead of form ID. 
So what you can do is, following the method in that article, but:
1> add a hidden field including the form name in your cf7 form:
[hidden form-name "Test GTM live"]
2> create a GTM variable using respons.0.value (0 if the hidden field is the 1st input of the form). I called that variable 'CF7formName'
3> And then include that variable in GTM Event tag sending the data to GA: Action: Form Name: {{CF7formName}}

**Comment by chrisblakley** [comment]
Looks like CF7 has moved development to Github, so I'll plan on making a pull request for this feature specifically.
https://github.com/takayukister/contact-form-7

**Comment by chrisblakley** [comment]
Looks like this isn't going to happen. Closing this issue at this point. If we ever switch contact form plugins we can revisit this idea.
