### ISSUE TITLE
Replace normal hyphens in phone number with non-breaking hyphen entities

### ISSUE THREAD

**Issue by patphg** [chrisblakley/Nebula#1567]
The phone number output by `nebula()->get_option('phone_number')` returns the phone number with regular hyphen characters (-).

Browsers naturally interpret these as good places to break the line but could be undesirable for a phone number.

The non-breaking hyphen entity is: `&#8209;`

**Comment by chrisblakley** [comment]
Recapping our convo:

Because `nebula()->get_option()` is just an interface for Nebula's options data we'd either need to:
 - Modify it so that all hyphens in all data return as non-breaking hyphens (kinda dangerous)
 - Make a function specifically for getting phone numbers (like addresses)
 - Recommend wrapping the function call in a `str_replace('-', '&#8209;', nebula()->get_option('phone_number'))`

I'm leaning to the string replace recommendation, but we can see if there are other ideas out there.

**Comment by chrisblakley** [comment]
Closing this for now, but if we come up with any additional ideas we can discuss/reopen as needed.
