### ISSUE TITLE
?debug "Window Loaded" timing is incorrect

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1592]
![image](https://user-images.githubusercontent.com/5795308/36517246-89bdab80-174f-11e8-8de5-028b57de0e64.png)

Noticed this happening on some of the newer sites I've been putting together.

**Comment by chrisblakley** [comment]
I actually have seen that before but never investigated it. When you refresh or if you console log the performance object again on the same load, it gets fixed (maybe not always). My best guess is that it is a race condition since that log happens on window load itself. Maybe a `setTimeout()` of 0 would kick it later in the stack?

If you are inclined, definitely add any clues you come up with and I'll look into it some more when I see it next too.

I would love to solve this without a hacky `setTimeout`, but we can get it working first and then make it better later.

**Comment by chrisblakley** [comment]
Ok, that was easy enough to test. My edit above is exactly what is happening. It seems counter-intuitive that during debug, where all the JS files _should_ be getting fresh files not cached files, the script can be ready so fast...

But, it could make sense that since the other scripts are taking longer to load, the asynchronous GA script (which is embedded in the `<head>`) could have already loaded within that time period.

Anyway, I think I'll just move the `performanceMetrics()` function into the window load listener without daisy chaining it.
