### ISSUE TITLE
a:not(.btn) can not be easily overwritten

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1644]
The CSS selector of `a:not(.btn)` can't easily be overwritten by the child stylesheet. Is there anything that can be done?

I think the Nebula button selectors are pretty specific, but the original Bootstrap ones may not be. Not sure how to handle this.

**Comment by chrisblakley** [comment]
This is also true for

```
body:not(.wp-admin) hr
```

**Comment by patmcneil** [comment]
After this issue was opened, the `a` selector has changed a bit to be `a:not(.btn):not(.wp-block-button__link)`

I am probably missing something because this seems too good to be true, but it looks like changing the master `_baseline.scss` back to just effect the `a` and not `a:not(.btn):not(.wp-block-button__link)`, and then styling the `a` in the child scss works?

Again I feel like I'm missing it but it's working for me in a sandbox.

**Comment by patmcneil** [comment]
OK, my previous comment was working because the properties I was testing (color, text-decoration, etc.) were already defined on the button and so weren't overriden. The issue flares up when a property which the button *doesn't* have is defined e.g. text-transform.

**Comment by chrisblakley** [comment]
Maybe `:where` could help here?

**Comment by chrisblakley** [comment]
The tough thing now is that `:where()` gets overwritten by the Bootstrap reboot CSS.

So I've used `:where` in the parent theme, and kept the `a:not()` alone in the child theme. That should be enough to close this for now, but I'd love to find an even better solution one day...
