### ISSUE TITLE
No author name on the header

### ISSUE THREAD

**Issue by xcibe95x** [chrisblakley/Nebula#1847]
Hello, i don't know why but theres no author name on the header.
![test](https://user-images.githubusercontent.com/19245385/55373902-f9c34700-5506-11e9-9d64-938615311319.png)

**Comment by chrisblakley** [comment]
Thanks for reporting this. I have some follow-up questions in order to try to recreate this.

- What version of WordPress and Nebula are you using? You can see this in the lower right of any admin page.
- Could you let me know what template this is using (and/or what post type it is)? Is this a regular post using `single.php`?
- Can you check the Appearance > Nebula Options > Functions and see if Author Bios is on or off?
- How about this Author's profile? Is their name set or empty?
- Do you typically use the Customizer for your site settings?

Any other settings/options you have changed, or other info could be helpful.

I want to make sure this works regardless of your settings, but I need to be able to recreate it first. Thanks again!

**Comment by xcibe95x** [comment]
WordPress 5.1.1
Nebula 6.11.1.6919 (Committed: April 1, 2019)
It is a regular post using single.php
Author Bios is turned on, but i also tried turning this off was one of my first toughts
The Author profile is all filled so i don't think it's the problem since on the front page the author works.
Been using the customizer to edit most of the things.
Every change i made to the source are gone since i reinstalled the template and have same issue
Using only 2 Plugins, Nebula Companion and Relevanssi.
Hope this helps.

https://cibe.playconstraints.com/guides/games/how-to-play-world-at-war-zombies-with-the-latest-hamachi/

**Comment by chrisblakley** [comment]
Do you have access to edit `single.php` directly? I'm curious if `get_the_author()` outputs anything in that area. Same with `get_the_author_meta('ID')`.

Viewing that site, the front page, archives, and category are all working fine (those all use `loop.php`), but the single.php template is the only one that isn't.

I'm also curious what `post_author(array('linked' => true, 'force' => false))` outputs (for some reason, the default value of `force` is true which overrides the Author Bios). I don't think that is what's causing this, but I will be fixing that as well. **Note:** this could be why the author is not linked on your website despite using the default function.

Some of these notes are for myself for tomorrow when I can really dive into this, but if you have any clarifications or tests you can try that'd be great too.

- `loop.php` calls this using `nebula()->post_meta('by')`
- `single.php` calls this using `nebula()->post_author()`

The `post_meta('by')` simply calls the default options of `nebula()->post_author()` so at first glance they are calling the same thing. So I'm not sure that's where the issue is, but still work looking into.

**Comment by chrisblakley** [comment]
@xcibe95x I was able to recreate and fix this issue. The problem was that sometimes the post data is unavailable outside of the loop, so I added some conditionals to make sure we always have the author ID. You should be able to run a theme update and see the author appear on the single post template.

Thanks again for reporting this issue.
