### ISSUE TITLE
get_search_form is outputting the form (sometimes) regardless of the echo parameter

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1926]
`get_search_form()` seems to be echoing the search form sometimes. I am not able to recreate this but @patmcneil was seeing it on his implementation.

In `metadata.php` for a conditional, Nebula checks if the site uses search `get_search_form(array('echo' => false))` and if so, it outputs some structured data.

What we're seeing is (somehow sometimes) the search form is output right there even though the `echo` parameter is `false`.

Nebula hooks into `get_search_form` to replace it with a Bootstrap form, but I'm still not sure why that gets output... Essentially `$args = array('echo' => false);` is false so it should not output...

WP docs: https://developer.wordpress.org/reference/functions/get_search_form/

**Comment by chrisblakley** [comment]
This is how it looks on my server. This makes sense:

- No params, it echoes and the `NULL` is because there is no `return`.
- echo false, it returns so we get it as a string.
- echo true, it echoes and the `NULL` is because there is no `return`. (same as the first bullet)

![Screen Shot 2019-06-04 at 7 29 18 PM](https://user-images.githubusercontent.com/6349678/58920250-3d9d1d00-86ff-11e9-914d-bfe4125798fb.png)

**Comment by chrisblakley** [comment]
Here's a screen of a server that *can* reproduce the issue. Same exact code as above. Notice that two forms are output for each call of `get_search_form()` the second form (which is the WordPress form) is doing the correct thing, but the first form (which is the Nebula/Bootstrap form) is being output first...

![Screen Shot 2019-06-04 at 8 23 54 PM](https://user-images.githubusercontent.com/6349678/58921943-e56a1900-8706-11e9-8080-b65d93b63b9b.png)

**Comment by patmcneil** [comment]
This had something to do with using

`add_action('pre_nebula_search_form', 'event_search_form');`

Inside of the `pre_` action I modify the `$form` variable to change some CSS classes. There was an `echo` in it, which was outputting the bootstrap form (seen above). After the `echo` replaced with a `return`, it disappears. 

The `pre_` action **does** `return` the `$form` but it did not output. To get around this, I modified the `search_form()` function slightly:

`$override = apply_filters('pre_nebula_search_form', null);`
`if ( isset($override) ){return $override;}` 

Note where instead of just `return;` after the `isset`, it now returns `$override` (which is set above by the filter which returns the modified `$form`).

**Comment by chrisblakley** [comment]
Good catch. I'll also pass the `$form` to the override filter as well so that can also be modified.

**Comment by chrisblakley** [comment]
I updated that `$override` return as well as a bunch of others too. Will push with next commit.
