### ISSUE TITLE
ScrollTo function is scrolling back up to nearly the top of the page

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1942]
https://gearside.com/nebula/functions/scrollto/

When clicking a link that is already in view, the page scrolls back to almost the top of the page. Maybe a math error or a `0` detection issue?

**Comment by chrisblakley** [comment]
Actually, the demo is working properly... When clicking the button it scrolls up to the `Usage` ID as intended.

Will need to recreate it on that project, @patmcneil, to see what could be happening...

**Comment by patphg** [comment]
The issue here was that the script checks to see how far offset from the top of the window the target is and then scrolls to this value. However, if you happen to click a link which scrolls to a target which is already in view at the top of the window, it scrolls you back up. Why? Let's run through it:

1. At the top of the page. Click link. Target is 1000 px from top of viewport. Scroll to 1000 px.
2. Now at target. Click link to scroll to this target (again). Target is 0px from top of viewport. Scroll window (back up) to 0 px.
3. At top of page again... 

The simplest fix I can come up with is instead of:

`var nOffset = Math.floor(target.offset().top-offset+pOffset)`

(where `nOffset` is the location of the target) I modified it to be:

`var nOffset = Math.floor(target.offset().top-offset+pOffset) + jQuery('body').scrollTop();`

So, the target point is the current scroll depth PLUS the offset of the target. If it's 0, it will just scroll to where it already is. I also implemented some logic so if `nOffset = 0` it doesn't bother running the animation jQuery. But I think you can handle that.

**Fuel for a separate issue:** how do I specify a global offset, when I don't have access to the <a> tag to add an offset value? E.G. anchor links created in the WordPress menu maker.

**Comment by patphg** [comment]
I also forgot to note that the `jQuery('body').scrollTop()` addition should happen to variables in the other scrollTo type handlers, too.

**Comment by patphg** [comment]
Potential global solution: create a nebula object something like:

`nebula.scrollOffset = {"x":0, "y":0}`

A developer could set this on the fly with JS. The `nebula.scrollTo` function checks if the option has been set, and takes it into account when doing the math.

**Comment by chrisblakley** [comment]
Ok this worked out well- thanks for doing the legwork on it.

I added an object to the `nebula` object called `scroll` which contains `offset` and `speed`. For now I'm not going to use `x` and `y` within the offset, but that's not to say that couldn't be modified in the future.

I'll get this pushed tonight so it can be used tomorrow.
