### ISSUE TITLE
Add a "Skip Video Controls" to Nebula Youtube Embed

### ISSUE THREAD

**Issue by patphg** [chrisblakley/Nebula#1960]
**Describe the Problem**
While using the tab key to navigate the site, when a user encounters a Nebula YouTube component, the tab key (properly) cycles through all of the video controls before continuing.

**Proposed Solution**
Add a `#skip-video-controls-x` tag before the video embed, and a matching `<a name="skip-video-controls-x`></a> after it, where `x` is a unique identifier (for multiple videos on a single page).

**Comment by chrisblakley** [comment]
I may opt to add a hook to allow developers to introduce this type of tag when they prefer.

My biggest concern is that it would be one more thing to tab through in order to save a potential 4 elements (logo, title, menu, and play button). There isn't often more than 1 video on a page, but if there were, maybe a hook would be sufficient for this idea.

![Screen Shot 2019-11-16 at 12 40 20 PM](https://user-images.githubusercontent.com/6349678/68996907-76285180-086e-11ea-877c-8c50ba70e23e.png)

**Comment by chrisblakley** [comment]
I was thinking about this some more this weekend– the actual embed itself is still controlled by the developer, not Nebula. Nebula only handles the video metadata so there isn't a way to add any kind of hook for this.

Here's an example:
```php
<?php $youtube_data = nebula()->video_meta('youtube', 'jtip7Gdcf0Q'); ?>
<div class="embed-responsive embed-responsive-16by9">
	<iframe id="<?php echo $youtube_data['id']; ?>" class="youtube embed-responsive-item" width="560" height="315" title="<?php echo $youtube_data['title']; ?>" src="//www.youtube.com/embed/<?php echo $youtube_data['id']; ?>?wmode=transparent&enablejsapi=1&rel=0" loading="lazy"></iframe>
</div>
```

So to achieve the skip controls idea you could do this:
```php
<?php $youtube_data = nebula()->video_meta('youtube', 'jtip7Gdcf0Q'); ?>
<div class="embed-responsive embed-responsive-16by9">
	<a class="skip-video-controls sr-only" href="#after-video-<?php echo $youtube_data['id']; ?>">Skip video controls</a>
	<iframe id="<?php echo $youtube_data['id']; ?>" class="youtube embed-responsive-item" width="560" height="315" title="<?php echo $youtube_data['title']; ?>" src="//www.youtube.com/embed/<?php echo $youtube_data['id']; ?>?wmode=transparent&enablejsapi=1&rel=0" loading="lazy"></iframe>
	<span id="after-video-<?php echo $youtube_data['id']; ?>"></span>
</div>
```
