### ISSUE TITLE
Auto-Indicators class for Bootstrap Carousel breaks indicator active states

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#2033]
I haven't ruled this out as a SEM specific issue yet but I thought I would submit it here for some testing and consideration. 

**Describe the Problem**
When using the `auto-indicators` to automatically add the carousel indicator markup to a Bootstrap Carousel, the indicators active states break. 

```html
<ol class="carousel-indicators">
  <li data-target="#taget-slider" data-slide-to="0" class="active"></li>
  <li data-target="#taget-slider" data-slide-to="1"></li>
  <li data-target="#taget-slider" data-slide-to="2"></li>
  <li data-target="#taget-slider" data-slide-to="3"></li>
</ol>
````
**Steps to Reproduce**
1. Go to https://www.semills.com/recipes-tips/tips-and-tricks/breakfast/
2. Click on... 
![btn](https://user-images.githubusercontent.com/30500449/86169127-22aa0180-bae7-11ea-9da7-dfeb1bad6569.JPG)
3. See the indicator not change to the active slide

**Expected Behavior**
The indicator should jump to the proper active state. Example here: https://www.betterthanbouillon.com/recipes-tips/make-it-better/roasting/

![success](https://user-images.githubusercontent.com/30500449/86169515-c1cef900-bae7-11ea-9510-d062ce39a348.gif)

**Screenshots**
![84296922-bc027b00-ab1a-11ea-8a73-91792e870656](https://user-images.githubusercontent.com/30500449/86169098-17ef6c80-bae7-11ea-8bac-a430bc9bd95c.gif)

**Environment Details**
Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Additional Information**
From what I have tested so far, the markup is identical and the only major difference is its order in the carousel container, which really shouldn't affect it at all.

**Comment by chrisblakley** [comment]
I'll definitely look into this, but two things I'm considering for this feature in future Nebula versions:

- I want to see how Bootstrap 5 #1990 handles carousels and if this feature is going to change at all
- Potentially removing the `auto-indicators` functionality completely from Nebula

It's never worked (visually) 100% since it's been implemented, but I have not yet experienced a functionality issue like this with it before.

**Comment by chrisblakley** [comment]
I am able to recreate this on this demo here:
https://gearside.com/nebula/examples/bootstrap-carousel/

**Comment by chrisblakley** [comment]
Ok, I think this was a hydration issue, so I moved the `nebula.initBootstrapFunctions();` to the DOM ready event listener (from the window load event). I will commit this to Github tonight, but that's the fix for retrofitting to older sites.

<img width="692" alt="Screen Shot 2020-06-30 at 4 33 13 PM" src="https://user-images.githubusercontent.com/6349678/86174614-fcd52a80-baef-11ea-8cce-70f3f2f9d0f9.png">

If that doesn't do the trick for some reason, feel free to re-open this issue!

**Comment by chrisblakley** [comment]
This is fixed in Bootstrap v5.

For reference:
```html
<div class="carousel-indicators">
	<button type="button" data-bs-target="#example-carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
	<button type="button" data-bs-target="#example-carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
	<button type="button" data-bs-target="#example-carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
</div>
```

https://nebula.gearside.com/examples/bootstrap-carousel/
