### ISSUE TITLE
Conflict bewteen Nebula and Woocommerce

### ISSUE THREAD

**Issue by PennyLava** [chrisblakley/Nebula#2131]
Hi there,

I am using Nebula as a theme for my e-commerce. The thing is that when I click on Appearance --> Customize --> Wordpress the system force the logout from my admin account and I see a white page with the text

You need a higher level of permission.
Sorry, you are not allowed to customize this site.

I tried the same process with the default wordpress theme Twenty Twenty One and it works fine as expected.

Can you please fix this?

Thanks

Fabiola

**Comment by chrisblakley** [comment]
Thanks for the heads-up– we can check into this.

**Comment by chrisblakley** [comment]
Looks like this was not a conflict with Woocommerce, but an overly aggressive method to clear caches when the Customizer was saved or closed (without saving). Basically site cookies were cleared at that point which caused the user to be signed out, so that part has been removed and it appears to be working much better now.

**Comment by PennyLava** [comment]
Thanks! Worked like a charm
