### ISSUE TITLE
Annual YouTube Block is Broken

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#2219]
_Version information can be found in the lower right of most WP admin screens_
**WordPress** 6.0.1
**Nebula** 10.3.8.597 

**Describe the Problem**
Using the YouTube Block. Displaying properly in the editor. No block output at all

**Steps to Reproduce**
1. Go to any nebula site
2. Add a youtube block to a page, publish
3. View the page
4. No block HTML is present

**Expected Behavior**
To see the YouTube Video on the page

**Screenshots**
Admin
![image](https://user-images.githubusercontent.com/30500449/185159082-b457b318-c4e2-4660-b173-49da790bf7d2.png)
Front End
![image](https://user-images.githubusercontent.com/30500449/185159208-5c099439-4b00-4ad1-a63a-c965e927cca5.png)

**Additional Information**
No errors output in the console but also no HTML from the block itself.

**Comment by chrisblakley** [comment]
I got it to reappear, but I'll be honest I have no idea what the issue was. I could recreate it, but when I run a diff between the working Vimeo block and the broken Youtube block they are identical.

I duplicated and meticulously converted the working Vimeo block into the "new" Youtube block and it is working again.

Two big changes that I made (which I don't think have any effect on the functionality) were:
- Just inlining the `render_callback` functions so they don't have to call another separate function
- Adding the Nebula version number to the block scripts so they are more easily updated avoiding the cache

Here's the "new" working Youtube block... pretty much the same as the old one...
```php
//Nebula Youtube Block
public function youtube_gutenberg_block(){
	if ( function_exists('register_block_type') ){
		//Editor Script
		wp_register_script(
			'nebula-youtube-block',
			get_template_directory_uri() . '/libs/Gutenberg/blocks/youtube/youtube.js',
			array('wp-blocks', 'wp-element'),
			$this->version('full')
		);

		register_block_type('nebula/youtube', array(
			'editor_script' => 'nebula-youtube-block',
			//'script' => 'nebula-youtube-block', //Use this to create the element in the "save" object of the block JS file
			'render_callback' => function($attribites, $content){ //Use this to create the element in PHP (With attributes passed as a parameter)
				$youtube_data = nebula()->video_meta('youtube', $attribites['videoID']);

				   return '<div class="nebula-youtube ratio ratio-16x9 ' . $attributes['className'] . '"><iframe id="' . $youtube_data['safetitle'] . '" class="youtube" width="1024" height="768" src="//www.youtube.com/embed/' . $youtube_data['id'] . '?wmode=transparent&enablejsapi=1&rel=0&t=' . $attribites['videoTimestamp'] . '" frameborder="0" allowfullscreen loading="lazy"></iframe></div>';
			},
		));
	}
}
```

**Comment by chrisblakley** [comment]
![giphy](https://user-images.githubusercontent.com/6349678/185197590-d9e0c0a4-b658-4d00-a954-de342da7f171.gif)

**Comment by chrisblakley** [comment]
I think the problem might literally be that something doesn't like the filename `youtube.js`. If I change it to just `yt.js` it seems to be working fine, so that's what I'm going with. 🤷
